### ISSUE TITLE
Update About and Contact pages

### ISSUE THREAD

**Issue by IdkwhatImD0ing** [IdkwhatImD0ing/SlugLoop#40]
- Basically, make the About Us page better in terms of formatting and spacing
   - Right now just has a bunch of text
   - Maybe make cards or something with profile pictures and links to websites
   - Also try to make sure there is no scrollbar on any device
 - Question Mark button seems a bit weird in terms of styling

**Comment by danchan020** [comment]
I can try to work on this, pls include instructions to start up server and client in readme.

**Comment by IdkwhatImD0ing** [comment]
> I can try to work on this, pls include prereq installations and instructions to start up server and client in readme.

Hello! Thank you for your interest in contributing to the project, but currently our project is still in a very early stage. We are trying to coordinate with faculty and staff on hardware related issues. 

There is a chance that we will have to revamp our entire codebase/structure. Due to this issue, we won't be able to accept any PRs. We anticipate that the hardware should be finalized after March 31st and will start accepting PRs.

Suggestions for frontend/backend chances are still welcome and we will take those into consideration. Instructions to start up server and client will be added soon.
